#config.yaml 
stt:
  name: whisper
  recording_time: 10
  silence_break: 2
  model_size: small
  sensibility: 500
asistente:
  spotify: False
  wake_word: lumi
  wake_word2: lumie
  wake_word3: lumia
  wake_word4: lummi
  wake_word5: lumii